/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 62821
 */
public class pages3 extends javax.swing.JFrame {

    /**
     * Creates new form pages4
     */
    public pages3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lblmanual = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        lbl1.setBackground(new java.awt.Color(204, 204, 204));
        lbl1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(204, 204, 204));
        lbl1.setText("BERKAH RENTAL");
        jPanel1.add(lbl1);
        lbl1.setBounds(80, 28, 130, 19);

        lbl2.setFont(new java.awt.Font("Sitka Text", 1, 28)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 191, 0));
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("PRICE LIST");
        jPanel1.add(lbl2);
        lbl2.setBounds(40, 53, 204, 36);

        lblmanual.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblmanual.setForeground(new java.awt.Color(255, 191, 0));
        lblmanual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmanual.setText("Manual");
        jPanel1.add(lblmanual);
        lblmanual.setBounds(50, 110, 74, 19);

        lbl4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 191, 0));
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setText("Matic");
        jPanel1.add(lbl4);
        lbl4.setBounds(180, 110, 74, 19);

        lbl5.setBackground(new java.awt.Color(204, 204, 204));
        lbl5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lbl5.setForeground(new java.awt.Color(204, 204, 204));
        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5.setText("12 Hours : Rp 500.000 ");
        jPanel1.add(lbl5);
        lbl5.setBounds(20, 160, 120, 16);

        lbl6.setBackground(new java.awt.Color(204, 204, 204));
        lbl6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl6.setForeground(new java.awt.Color(204, 204, 204));
        lbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl6.setText("1 Day : Rp 900.000 ");
        jPanel1.add(lbl6);
        lbl6.setBounds(20, 190, 120, 16);

        lbl7.setBackground(new java.awt.Color(204, 204, 204));
        lbl7.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lbl7.setForeground(new java.awt.Color(204, 204, 204));
        lbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl7.setText("2 Day : Rp 1.500.000 ");
        jPanel1.add(lbl7);
        lbl7.setBounds(20, 220, 120, 16);

        lbl8.setBackground(new java.awt.Color(204, 204, 204));
        lbl8.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lbl8.setForeground(new java.awt.Color(204, 204, 204));
        lbl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl8.setText("3 Day : Rp 2.250.000 ");
        jPanel1.add(lbl8);
        lbl8.setBounds(20, 250, 120, 16);

        lbl9.setBackground(new java.awt.Color(204, 204, 204));
        lbl9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl9.setForeground(new java.awt.Color(204, 204, 204));
        lbl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl9.setText("12 Hours : Rp 600.000 ");
        jPanel1.add(lbl9);
        lbl9.setBounds(157, 160, 130, 20);

        lbl10.setBackground(new java.awt.Color(204, 204, 204));
        lbl10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl10.setForeground(new java.awt.Color(204, 204, 204));
        lbl10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl10.setText("1 Day : Rp 1.000.000 ");
        jPanel1.add(lbl10);
        lbl10.setBounds(160, 190, 120, 16);

        lbl11.setBackground(new java.awt.Color(204, 204, 204));
        lbl11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl11.setForeground(new java.awt.Color(204, 204, 204));
        lbl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl11.setText("2 Day : Rp 1.600.000 ");
        jPanel1.add(lbl11);
        lbl11.setBounds(160, 220, 120, 16);

        lbl12.setBackground(new java.awt.Color(204, 204, 204));
        lbl12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl12.setForeground(new java.awt.Color(204, 204, 204));
        lbl12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl12.setText("3 Day : Rp 2.350.000 ");
        jPanel1.add(lbl12);
        lbl12.setBounds(160, 250, 120, 16);

        jButton1.setBackground(new java.awt.Color(80, 79, 79));
        jButton1.setForeground(new java.awt.Color(255, 191, 0));
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 340, 72, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\62821\\Downloads\\Untitled design (9).png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 300, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
        pages4 button = new pages4();
        button.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pages3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pages3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pages3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pages3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pages3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblmanual;
    // End of variables declaration//GEN-END:variables
}
