/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 62821
 */
public class pricelist extends javax.swing.JFrame {

    /**
     * Creates new form pagess
     */
    public pricelist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lblmanual = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lblmanual1 = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        lbl16 = new javax.swing.JLabel();
        lbl17 = new javax.swing.JLabel();
        lbl18 = new javax.swing.JLabel();
        lbl19 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        nextButton1 = new javax.swing.JButton();

        lbl1.setBackground(new java.awt.Color(204, 204, 204));
        lbl1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(204, 204, 204));
        lbl1.setText("BERKAH RENTAL");

        lbl2.setFont(new java.awt.Font("Sitka Text", 1, 28)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 191, 0));
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("PRICE LIST");

        lblmanual.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblmanual.setForeground(new java.awt.Color(255, 191, 0));
        lblmanual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmanual.setText("Manual");

        lbl4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 191, 0));
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setText("Matic");

        lbl5.setBackground(new java.awt.Color(204, 204, 204));
        lbl5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lbl5.setForeground(new java.awt.Color(204, 204, 204));
        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5.setText("12 Hours : Rp 500.000 ");

        lbl9.setBackground(new java.awt.Color(204, 204, 204));
        lbl9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl9.setForeground(new java.awt.Color(204, 204, 204));
        lbl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl9.setText("12 Hours : Rp 600.000 ");

        lbl6.setBackground(new java.awt.Color(204, 204, 204));
        lbl6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl6.setForeground(new java.awt.Color(204, 204, 204));
        lbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl6.setText("1 Day : Rp 900.000 ");

        lbl10.setBackground(new java.awt.Color(204, 204, 204));
        lbl10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl10.setForeground(new java.awt.Color(204, 204, 204));
        lbl10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl10.setText("1 Day : Rp 1.000.000 ");

        lbl7.setBackground(new java.awt.Color(204, 204, 204));
        lbl7.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lbl7.setForeground(new java.awt.Color(204, 204, 204));
        lbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl7.setText("2 Day : Rp 1.500.000 ");

        lbl11.setBackground(new java.awt.Color(204, 204, 204));
        lbl11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl11.setForeground(new java.awt.Color(204, 204, 204));
        lbl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl11.setText("2 Day : Rp 1.600.000 ");

        lbl8.setBackground(new java.awt.Color(204, 204, 204));
        lbl8.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lbl8.setForeground(new java.awt.Color(204, 204, 204));
        lbl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl8.setText("3 Day : Rp 2.250.000 ");

        lbl12.setBackground(new java.awt.Color(204, 204, 204));
        lbl12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl12.setForeground(new java.awt.Color(204, 204, 204));
        lbl12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl12.setText("3 Day : Rp 2.350.000 ");

        nextButton.setBackground(new java.awt.Color(80, 79, 79));
        nextButton.setForeground(new java.awt.Color(255, 191, 0));
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        lbl3.setBackground(new java.awt.Color(204, 204, 204));
        lbl3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(204, 204, 204));
        lbl3.setText("BERKAH RENTAL");
        jPanel1.add(lbl3);
        lbl3.setBounds(80, 28, 130, 19);

        lbl13.setFont(new java.awt.Font("Sitka Text", 1, 28)); // NOI18N
        lbl13.setForeground(new java.awt.Color(255, 191, 0));
        lbl13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl13.setText("PRICE LIST");
        jPanel1.add(lbl13);
        lbl13.setBounds(40, 53, 204, 36);

        lblmanual1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblmanual1.setForeground(new java.awt.Color(255, 191, 0));
        lblmanual1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmanual1.setText("Manual");
        jPanel1.add(lblmanual1);
        lblmanual1.setBounds(40, 100, 74, 19);

        lbl14.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lbl14.setForeground(new java.awt.Color(255, 191, 0));
        lbl14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl14.setText("Matic");
        jPanel1.add(lbl14);
        lbl14.setBounds(190, 100, 74, 19);

        lbl15.setBackground(new java.awt.Color(204, 204, 204));
        lbl15.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lbl15.setForeground(new java.awt.Color(204, 204, 204));
        lbl15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl15.setText("12 Hours : Rp 500.000 ");
        jPanel1.add(lbl15);
        lbl15.setBounds(20, 130, 120, 16);

        lbl16.setBackground(new java.awt.Color(204, 204, 204));
        lbl16.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl16.setForeground(new java.awt.Color(204, 204, 204));
        lbl16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl16.setText("12 Hours : Rp 600.000 ");
        jPanel1.add(lbl16);
        lbl16.setBounds(160, 130, 130, 20);

        lbl17.setBackground(new java.awt.Color(204, 204, 204));
        lbl17.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl17.setForeground(new java.awt.Color(204, 204, 204));
        lbl17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl17.setText("1 Day : Rp 900.000 ");
        jPanel1.add(lbl17);
        lbl17.setBounds(20, 170, 120, 16);

        lbl18.setBackground(new java.awt.Color(204, 204, 204));
        lbl18.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl18.setForeground(new java.awt.Color(204, 204, 204));
        lbl18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl18.setText("1 Day : Rp 1.000.000 ");
        jPanel1.add(lbl18);
        lbl18.setBounds(160, 170, 120, 16);

        lbl19.setBackground(new java.awt.Color(204, 204, 204));
        lbl19.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lbl19.setForeground(new java.awt.Color(204, 204, 204));
        lbl19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl19.setText("2 Day : Rp 1.500.000 ");
        jPanel1.add(lbl19);
        lbl19.setBounds(20, 210, 120, 16);

        lbl20.setBackground(new java.awt.Color(204, 204, 204));
        lbl20.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl20.setForeground(new java.awt.Color(204, 204, 204));
        lbl20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl20.setText("2 Day : Rp 1.600.000 ");
        jPanel1.add(lbl20);
        lbl20.setBounds(160, 210, 120, 16);

        lbl21.setBackground(new java.awt.Color(204, 204, 204));
        lbl21.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lbl21.setForeground(new java.awt.Color(204, 204, 204));
        lbl21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl21.setText("3 Day : Rp 2.250.000 ");
        jPanel1.add(lbl21);
        lbl21.setBounds(20, 250, 120, 16);

        lbl22.setBackground(new java.awt.Color(204, 204, 204));
        lbl22.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl22.setForeground(new java.awt.Color(204, 204, 204));
        lbl22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl22.setText("3 Day : Rp 2.350.000 ");
        jPanel1.add(lbl22);
        lbl22.setBounds(160, 250, 120, 16);

        nextButton1.setBackground(new java.awt.Color(80, 79, 79));
        nextButton1.setForeground(new java.awt.Color(255, 191, 0));
        nextButton1.setText("Next");
        nextButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(nextButton1);
        nextButton1.setBounds(100, 330, 130, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(469, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed

    }//GEN-LAST:event_nextButtonActionPerformed

    private void nextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton1ActionPerformed
        this.setVisible(false);
        orderPages button = new orderPages();
        button.setVisible(true);
    }//GEN-LAST:event_nextButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pricelist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pricelist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pricelist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pricelist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pricelist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblmanual;
    private javax.swing.JLabel lblmanual1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton nextButton1;
    // End of variables declaration//GEN-END:variables
}
