/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.berkahrentalkendaraan;

/**
 *
 * @author 62821
 */
public class outputPages extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
   
    int uangPembeli;
    int uangKembalian;

    public outputPages() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        yourPhone = new javax.swing.JLabel();
        yourName = new javax.swing.JLabel();
        yourAddress = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        finalDuration = new javax.swing.JLabel();
        finalTransmision = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        totalHarga = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\62821\\Downloads\\Untitled design (16).png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Durasi      :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 300, 70, 30);

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Pesanan Anda");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 220, 90, 30);

        jLabel5.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Transmisi :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 260, 80, 30);

        yourPhone.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(yourPhone);
        yourPhone.setBounds(210, 170, 340, 30);

        yourName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(yourName);
        yourName.setBounds(210, 90, 340, 30);

        yourAddress.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(yourAddress);
        yourAddress.setBounds(210, 130, 340, 30);

        jLabel6.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Nama    :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 90, 60, 30);

        jLabel7.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Alamat   :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 130, 60, 30);

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("No Telp :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 170, 60, 30);

        finalDuration.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(finalDuration);
        finalDuration.setBounds(230, 300, 180, 30);

        finalTransmision.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(finalTransmision);
        finalTransmision.setBounds(230, 260, 180, 30);

        jLabel12.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("PESANAN ANDA ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 20, 200, 40);

        nextButton.setBackground(new java.awt.Color(153, 153, 153));
        nextButton.setForeground(new java.awt.Color(255, 255, 255));
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nextButton);
        nextButton.setBounds(500, 380, 80, 23);

        totalHarga.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        totalHarga.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(totalHarga);
        totalHarga.setBounds(230, 350, 180, 30);

        jLabel14.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("TOTALNYA :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(50, 350, 90, 30);

        backButton.setBackground(new java.awt.Color(153, 153, 153));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(60, 450, 80, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\ESQ BS\\Kuliah\\Dasar Pemograman\\netbeans\\New Folder\\ProjectDaspro\\BerkahRentalKendaraan\\src\\main\\java\\com\\mycompany\\berkahrentalkendaraan\\Untitled design (16).png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        this.setVisible(false);
        lastPages button = new lastPages();
        button.setVisible(true);          
// TODO add your handling code here:
    }//GEN-LAST:event_nextButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        orderPages button = new orderPages();
        button.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(outputPages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(outputPages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(outputPages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(outputPages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new outputPages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    public javax.swing.JLabel finalDuration;
    public javax.swing.JLabel finalTransmision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextButton;
    public javax.swing.JLabel totalHarga;
    public javax.swing.JLabel yourAddress;
    public javax.swing.JLabel yourName;
    public javax.swing.JLabel yourPhone;
    // End of variables declaration//GEN-END:variables
}
